import { DataTypes } from 'sequelize';
import connection_db from '../../database/config/database';

const ClienteBeneficiarioProductionModel = connection_db.define(
  'ClienteBeneficiarioProductionModel',
  {
    id: {
      type: DataTypes.CHAR(36),
      primaryKey: true,
      allowNull: false,
    },
    operadora: DataTypes.STRING,
    convenio: DataTypes.STRING,
    grupo: DataTypes.STRING,
    subestipulante: DataTypes.STRING,
    data_proximo_reajuste: DataTypes.STRING,
    codigo_do_contrato: DataTypes.STRING,
    data_de_cancelamento: DataTypes.STRING,
    motivo_de_cancelamento: DataTypes.STRING,
    data_de_exclusao: DataTypes.STRING,
    numero_da_proposta: DataTypes.STRING,
    data_de_inclusao: DataTypes.STRING,
    data_de_assinatura: DataTypes.STRING,
    dias_de_permanencia: DataTypes.STRING,
    dia_vencimento: DataTypes.STRING,
    plano: DataTypes.STRING,
    acomodacao: DataTypes.STRING,
    produto: DataTypes.STRING,
    documento_corretor: DataTypes.STRING,
    codigo_corretor: DataTypes.STRING,
    nome_corretor: DataTypes.STRING,
    grupo_corretor: DataTypes.STRING,
    documento_supervisor: DataTypes.STRING,
    nome_supervisor: DataTypes.STRING,
    documento_corretora: DataTypes.STRING,
    nome_corretora: DataTypes.TEXT,
    grupo_corretora: DataTypes.STRING,
    documento_angiariador: DataTypes.STRING,
    angiariador: DataTypes.STRING,
    nome_responsavel_financeiro: DataTypes.TEXT,
    cpf_responsavel: DataTypes.STRING,
    id_beneficiario: DataTypes.STRING,
    codigo_do_beneficiario: DataTypes.STRING,
    marca_optica: DataTypes.STRING,
    marca_optica_opcional: DataTypes.STRING,
    nome_do_beneficiario: DataTypes.TEXT,
    data_de_nascimento: DataTypes.STRING,
    idade: DataTypes.STRING,
    orgao_emissor: DataTypes.STRING,
    cpf: {
        type: DataTypes.STRING,
        allowNull: false
    },
    rg: DataTypes.STRING,
    cns: DataTypes.STRING,
    dnv: DataTypes.STRING,
    pis: DataTypes.STRING,
    nome_da_mae: DataTypes.TEXT,
    endereco: DataTypes.TEXT,
    numero: DataTypes.STRING,
    complemento: DataTypes.TEXT,
    bairro: DataTypes.STRING,
    municipio: DataTypes.STRING,
    uf: DataTypes.STRING,
    cep: DataTypes.STRING,
    ddd_telefone: DataTypes.STRING,
    telefone: DataTypes.STRING,
    ddd_celular: DataTypes.STRING,
    celular: DataTypes.STRING,
    email_principal: DataTypes.STRING,
    email_secundario: DataTypes.TEXT,
    altura: DataTypes.STRING,
    peso: DataTypes.STRING,
    imc: DataTypes.STRING,
    vigencia: DataTypes.STRING,
    carencia: DataTypes.STRING,
    estado_civil: DataTypes.STRING,
    tipo_de_beneficiario: DataTypes.STRING,
    sexo: DataTypes.STRING,
    parentesco: DataTypes.STRING,
    status_do_beneficiario: DataTypes.STRING,
    forma_de_ajuste: DataTypes.STRING,
    ajuste: DataTypes.STRING,
    origem_de_venda: DataTypes.STRING,
    valor_do_contrato: DataTypes.STRING,
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
    }
  },
  {
    tableName: 'automation_cliente_digital_beneficiarios',
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  }
);

export default ClienteBeneficiarioProductionModel;