module.exports = (sequelize, Sequelize) => {
    const Beneficiario = sequelize.define("automation_cliente_digital_beneficiarios",
        {
            id: {
                type: Sequelize.UUID,
                defaultValue: Sequelize.UUIDV4,
                primaryKey: true,
            },
            operadora: { type: Sequelize.STRING },
            convenio: { type: Sequelize.STRING },
            grupo: { type: Sequelize.STRING },
            subestipulante: { type: Sequelize.STRING },
            data_proximo_reajuste: { type: Sequelize.STRING },
            codigo_do_contrato: { type: Sequelize.STRING },
            data_de_cancelamento: { type: Sequelize.STRING },
            motivo_de_cancelamento: { type: Sequelize.STRING },
            data_de_exclusao: { type: Sequelize.STRING },
            numero_da_proposta: { type: Sequelize.STRING },
            data_de_inclusao: { type: Sequelize.STRING },
            data_de_assinatura: { type: Sequelize.STRING },
            dias_de_permanencia: { type: Sequelize.STRING },
            dia_vencimento: { type: Sequelize.STRING },
            plano: { type: Sequelize.STRING },
            acomodacao: { type: Sequelize.STRING },
            produto: { type: Sequelize.STRING },
            documento_corretor: { type: Sequelize.STRING },
            codigo_corretor: { type: Sequelize.STRING },
            nome_corretor: { type: Sequelize.STRING },
            grupo_corretor: { type: Sequelize.STRING },
            documento_supervisor: { type: Sequelize.STRING },
            nome_supervisor: { type: Sequelize.STRING },
            documento_corretora: { type: Sequelize.STRING },
            nome_corretora: { type: Sequelize.STRING },
            grupo_corretora: { type: Sequelize.STRING },
            documento_angariador: { type: Sequelize.STRING },
            angariador: { type: Sequelize.STRING },
            nome_responsavel_financeiro: { type: Sequelize.STRING },
            cpf_responsavel: { type: Sequelize.STRING },
            id_beneficiario: { type: Sequelize.STRING },
            codigo_do_beneficiario: { type: Sequelize.STRING },
            marca_optica: { type: Sequelize.STRING },
            marca_optica_opcional: { type: Sequelize.STRING },
            nome_do_beneficiario: { type: Sequelize.STRING },
            data_de_nascimento: { type: Sequelize.STRING },
            idade: { type: Sequelize.STRING },
            rg: { type: Sequelize.STRING },
            orgao_emissor: { type: Sequelize.STRING },
            cpf: { type: Sequelize.STRING },
            dnv: { type: Sequelize.STRING },
            cns: { type: Sequelize.STRING },
            pis: { type: Sequelize.STRING },
            nome_da_mae: { type: Sequelize.STRING },
            endereco: { type: Sequelize.STRING },
            numero: { type: Sequelize.STRING },
            complemento: { type: Sequelize.STRING },
            bairro: { type: Sequelize.STRING },
            municipio: { type: Sequelize.STRING },
            uf: { type: Sequelize.STRING },
            cep: { type: Sequelize.STRING },
            ddd_telefone: { type: Sequelize.STRING },
            telefone: { type: Sequelize.STRING },
            ddd_celular: { type: Sequelize.STRING },
            celular: { type: Sequelize.STRING },
            email_principal: { type: Sequelize.STRING },
            email_secundario: { type: Sequelize.STRING },
            altura: { type: Sequelize.STRING },
            peso: { type: Sequelize.STRING },
            imc: { type: Sequelize.STRING },
            vigencia: { type: Sequelize.STRING },
            carencia: { type: Sequelize.STRING },
            estado_civil: { type: Sequelize.STRING },
            tipo_de_beneficiario: { type: Sequelize.STRING },
            sexo: { type: Sequelize.STRING },
            parentesco: { type: Sequelize.STRING },
            status_do_beneficiario: { type: Sequelize.STRING },
            forma_de_ajuste: { type: Sequelize.STRING },
            ajuste: { type: Sequelize.STRING },
            origem_de_venda: { type: Sequelize.STRING },
            valor_contrato: { type: Sequelize.STRING },
        },
        {
            timestamps: false
        }
    );

    return Beneficiario;
};
